# fly.toml app configuration file generated for inkami-api on 2025-11-16T05:28:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'inkami-api'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  APP_ENV = 'prod'
  JOB_QUEUE_NAME = 'inkami'
  PORT = '8080'
  FRONTEND_URL = 'https://jacixn.github.io/INKAMI'

[processes]
  web = 'poetry run uvicorn app.main:app --host 0.0.0.0 --port 8080'
  worker = 'poetry run python -m app.workers.worker'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["web"]
  

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
